### PR TITLE
Update branch with mamedev/mame

### PR DESCRIPTION
**Pull request by phileveritt**
homebrew branch needs newer header files not present from forked repo so fetched from mamedev/main.

### CODE REVIEW

**Comment by phileveritt** [comment]
Screenshot 2023-12-29 at 10 21 49 PM

Built and tested on macOS

**Comment by phileveritt** [comment]
the action/workflows are updated in this PR too, so hopefully they'll start passing in future PRs - so much red...

**Comment by roscopeco** [comment]
Thanks for this! 

It looks like `3rdparty/asmjit/src/asmjit/core/emitterutils.cpp` might have been missed during merge, there are still some conflicts in there (e.g. https://github.com/roscopeco/mame/blob/aec4602d572603ef4f2afa4bf659f748e6b05fee/3rdparty/asmjit/src/asmjit/core/emitterutils.cpp#L19).

**Comment by phileveritt** [comment]
> Thanks for this!
> 
> It looks like `3rdparty/asmjit/src/asmjit/core/emitterutils.cpp` might have been missed during merge, there are still some conflicts in there (e.g.
> 
> https://github.com/roscopeco/mame/blob/aec4602d572603ef4f2afa4bf659f748e6b05fee/3rdparty/asmjit/src/asmjit/core/emitterutils.cpp#L19
> 
> ).

thanks - updated

**Comment by roscopeco** [comment]
Thanks again for this, nice work!

**Pull request merged**
